<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>SpiceDB.Client</RootNamespace>
    <AssemblyName>SpiceDB.Client</AssemblyName>
    <Description>Idiomatic C# client for SpiceDB</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.Net.Client" Version="2.80.0" />
    <PackageReference Include="Google.Protobuf" Version="3.35.0" />
    <PackageReference Include="Grpc.Core.Api" Version="2.80.0" />
  </ItemGroup>

  <!-- Reference the proto-generated client project -->
  <ItemGroup>
    <ProjectReference Include="../../proto-clients/spicedb-csharp-proto/SpiceDB.Proto.csproj" />
  </ItemGroup>

</Project>
