package python

import (
	"testing"

	"github.com/authzed/spicedb-clients/spicedb-gen/schema"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestLanguage(t *testing.T) {
	g := &Generator{}
	assert.Equal(t, "python", g.Language())
}

func TestToPascalCase(t *testing.T) {
	for input, expected := range map[string]string{
		"user":         "User",
		"team_member":  "TeamMember",
		"ip_range":     "IpRange",
		"time_window":  "TimeWindow",
		"already":      "Already",
	} {
		assert.Equal(t, expected, toPascalCase(input), "input=%q", input)
	}
}

func TestToSnakeCase(t *testing.T) {
	for input, expected := range map[string]string{
		"user":          "user",
		"team_member":   "team_member",
		"TeamMember":    "team_member",
		"CamelCase":     "camel_case",
		"with_already":  "with_already",
	} {
		assert.Equal(t, expected, toSnakeCase(input), "input=%q", input)
	}
}

func TestEscapeKeyword(t *testing.T) {
	// Hard keywords get a trailing underscore.
	for _, kw := range []string{"class", "def", "del", "from", "if", "for", "return", "type"} {
		assert.Equal(t, kw+"_", escapeKeyword(kw))
	}
	// Soft keywords (3.10+) also get escaped.
	assert.Equal(t, "match_", escapeKeyword("match"))
	assert.Equal(t, "case_", escapeKeyword("case"))
	// Commonly-shadowed builtins also get escaped.
	assert.Equal(t, "id_", escapeKeyword("id"))
	assert.Equal(t, "list_", escapeKeyword("list"))
	// Non-keywords pass through.
	assert.Equal(t, "viewer", escapeKeyword("viewer"))
	assert.Equal(t, "edit", escapeKeyword("edit"))
}

func TestCelTypeToPyType(t *testing.T) {
	for input, expected := range map[string]string{
		"string":       "str",
		"int":          "int",
		"uint":         "int",
		"double":       "float",
		"bool":         "bool",
		"duration":     "str",
		"timestamp":    "str",
		"unknown_type": "Any",
	} {
		assert.Equal(t, expected, celTypeToPyType(input), "input=%q", input)
	}
}

func TestGenerateSampleSchema(t *testing.T) {
	s, err := schema.ParseFile("../testdata/sample.zed")
	require.NoError(t, err)

	g := &Generator{}
	files, err := g.Generate(s, nil)
	require.NoError(t, err)
	require.Len(t, files, 1)
	assert.Equal(t, "permissions.py", files[0].Path)

	output := string(files[0].Content)

	// Header
	assert.Contains(t, output, "# Code generated by spicedb-gen. DO NOT EDIT.")

	// Imports
	assert.Contains(t, output, "from __future__ import annotations")
	assert.Contains(t, output, "from collections.abc import AsyncIterator")
	assert.Contains(t, output, "from dataclasses import dataclass")
	assert.Contains(t, output, "from datetime import datetime")
	assert.Contains(t, output, "from typing import Any, ClassVar, TypeAlias, overload")
	assert.Contains(t, output, "from spicedb import SpiceDBClient, Transaction, Relationship, Filter")
	assert.Contains(t, output, "from spicedb.consistency import Consistency")

	// Base value types
	assert.Contains(t, output, "class Permission:")
	assert.Contains(t, output, "class PermissionRef:")
	assert.Contains(t, output, "class TypedRelationship:")
}
