package python

import (
	"testing"

	"github.com/authzed/spicedb-clients/spicedb-gen/schema"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestLanguage(t *testing.T) {
	g := &Generator{}
	assert.Equal(t, "python", g.Language())
}

func TestToPascalCase(t *testing.T) {
	for input, expected := range map[string]string{
		"user":         "User",
		"team_member":  "TeamMember",
		"ip_range":     "IpRange",
		"time_window":  "TimeWindow",
		"already":      "Already",
	} {
		assert.Equal(t, expected, toPascalCase(input), "input=%q", input)
	}
}

func TestToSnakeCase(t *testing.T) {
	for input, expected := range map[string]string{
		"user":          "user",
		"team_member":   "team_member",
		"TeamMember":    "team_member",
		"CamelCase":     "camel_case",
		"with_already":  "with_already",
	} {
		assert.Equal(t, expected, toSnakeCase(input), "input=%q", input)
	}
}

func TestEscapeKeyword(t *testing.T) {
	// Hard keywords get a trailing underscore.
	for _, kw := range []string{"class", "def", "del", "from", "if", "for", "return", "type"} {
		assert.Equal(t, kw+"_", escapeKeyword(kw))
	}
	// Soft keywords (3.10+) also get escaped.
	assert.Equal(t, "match_", escapeKeyword("match"))
	assert.Equal(t, "case_", escapeKeyword("case"))
	// Commonly-shadowed builtins also get escaped.
	assert.Equal(t, "id_", escapeKeyword("id"))
	assert.Equal(t, "list_", escapeKeyword("list"))
	// Non-keywords pass through.
	assert.Equal(t, "viewer", escapeKeyword("viewer"))
	assert.Equal(t, "edit", escapeKeyword("edit"))
}

func TestCelTypeToPyType(t *testing.T) {
	for input, expected := range map[string]string{
		"string":       "str",
		"int":          "int",
		"uint":         "int",
		"double":       "float",
		"bool":         "bool",
		"duration":     "str",
		"timestamp":    "str",
		"unknown_type": "Any",
	} {
		assert.Equal(t, expected, celTypeToPyType(input), "input=%q", input)
	}
}

func TestGenerateSampleSchema(t *testing.T) {
	s, err := schema.ParseFile("../testdata/sample.zed")
	require.NoError(t, err)

	g := &Generator{}
	files, err := g.Generate(s, nil)
	require.NoError(t, err)
	require.Len(t, files, 1)
	assert.Equal(t, "permissions.py", files[0].Path)

	output := string(files[0].Content)

	// Header
	assert.Contains(t, output, "# Code generated by spicedb-gen. DO NOT EDIT.")

	// Imports
	assert.Contains(t, output, "from __future__ import annotations")
	assert.Contains(t, output, "from collections.abc import AsyncIterator")
	assert.Contains(t, output, "from dataclasses import dataclass")
	assert.Contains(t, output, "from datetime import datetime")
	assert.Contains(t, output, "from typing import Any, ClassVar, TypeAlias, overload")
	assert.Contains(t, output, "from spicedb import SpiceDBClient, Transaction, Relationship, Filter")
	assert.Contains(t, output, "from spicedb.consistency import Consistency")

	// Base value types — all frozen dataclasses
	assert.Contains(t, output, "@dataclass(frozen=True)\nclass Permission:")
	assert.Contains(t, output, "@dataclass(frozen=True)\nclass PermissionRef:")
	assert.Contains(t, output, "@dataclass(frozen=True)\nclass TypedRelationship:")

	// Caveat context dataclasses
	assert.Contains(t, output, "class IpRangeContext:")
	assert.Contains(t, output, "allowed_cidr: str | None = None")
	assert.Contains(t, output, "class TimeWindowContext:")
	assert.Contains(t, output, "end: str | None = None")
	assert.Contains(t, output, "start: str | None = None")
	assert.Contains(t, output, "def _to_dict(self) -> dict[str, Any]:")

	// The dict-key in _to_dict must be the raw schema param name, not the
	// Python identifier, so SpiceDB's CEL evaluator can bind it correctly.
	assert.Contains(t, output, `d["allowed_cidr"] = self.allowed_cidr`)

	// Subject ref dataclasses — base
	assert.Contains(t, output, "class User:")
	assert.Contains(t, output, "_type: ClassVar[str] = \"user\"")

	// Sub-relation ref (referenced as a subject)
	assert.Contains(t, output, "class TeamMember:")
	assert.Contains(t, output, "_relation: ClassVar[str] = \"member\"")

	// Caveated variants
	assert.Contains(t, output, "class UserIpRange:")
	assert.Contains(t, output, "context: IpRangeContext")
	assert.Contains(t, output, "_caveat: ClassVar[str] = \"ip_range\"")
	assert.Contains(t, output, "class UserTimeWindow:")

	// Internal accessors on every ref
	assert.Contains(t, output, "def _subject_ref(self) -> tuple[str, str, str]:")
	assert.Contains(t, output, "def _caveat_info(self) -> tuple[str, dict[str, Any]] | None:")
	assert.Contains(t, output, "def _expiration(self) -> datetime | None:")

	// Caveat builder methods on User
	assert.Contains(t, output, "def with_ip_range(self, ctx: IpRangeContext) -> UserIpRange:")
	assert.Contains(t, output, "def with_time_window(self, ctx: TimeWindowContext) -> UserTimeWindow:")

	// UserIpRange's _caveat_info returns the right values
	assert.Contains(t, output, "return \"ip_range\", self.context._to_dict()")

	// Document resource ref
	assert.Contains(t, output, "class Document:")
	assert.Contains(t, output, "    @property")
	assert.Contains(t, output, "    def view(self) -> _DocumentViewPermission:")
	assert.Contains(t, output, "    def edit(self) -> _DocumentEditPermission:")
	assert.Contains(t, output, "    def delete(self) -> _DocumentDeletePermission:")
	assert.Contains(t, output, "    def viewer(self, subject: DocumentViewerSubject) -> TypedRelationship:")
	assert.Contains(t, output, "    def editor(self, subject: DocumentEditorSubject) -> TypedRelationship:")
	assert.Contains(t, output, "    def owner(self, subject: DocumentOwnerSubject) -> TypedRelationship:")

	// Team resource ref — sub-ref property + renamed relation write
	assert.Contains(t, output, "class Team:")
	assert.Contains(t, output, "    def member(self) -> TeamMember:")            // @property
	assert.Contains(t, output, "    def for_member(self, subject: TeamMemberSubject) -> TypedRelationship:")

	// Sub-ref property body
	assert.Contains(t, output, "return TeamMember(id=self.id)")

	// Per-permission narrowing subclasses — must be frozen dataclasses, since
	// they're constructed at @property access time and shared across calls.
	assert.Contains(t, output, "@dataclass(frozen=True)\nclass _DocumentViewPermission(Permission): pass")
	assert.Contains(t, output, "@dataclass(frozen=True)\nclass _DocumentEditPermission(Permission): pass")
	assert.Contains(t, output, "@dataclass(frozen=True)\nclass _DocumentDeletePermission(Permission): pass")
	assert.Contains(t, output, "@dataclass(frozen=True)\nclass _DocumentViewRef(PermissionRef): pass")
	assert.Contains(t, output, "@dataclass(frozen=True)\nclass _DocumentEditRef(PermissionRef): pass")
	assert.Contains(t, output, "@dataclass(frozen=True)\nclass _DocumentDeleteRef(PermissionRef): pass")
}

// TestCaveatParamKeywordCollision verifies that when a caveat parameter's name
// collides with a Python keyword/builtin, the generator:
//   - Escapes the Python identifier (e.g. "id" -> "id_") for the dataclass field
//   - Preserves the raw name as the dict key, so CEL evaluation receives "id",
//     not "id_". A bug in the dict-key mapping would otherwise silently break
//     caveat evaluation at runtime.
func TestPySubjectRefName(t *testing.T) {
	assert.Equal(t, "User", pySubjectRefName(schema.SubjectType{Definition: "user"}))
	assert.Equal(t, "TeamMember", pySubjectRefName(schema.SubjectType{Definition: "team", Relation: "member"}))
	assert.Equal(t, "UserIpRange", pySubjectRefName(schema.SubjectType{Definition: "user", CaveatName: "ip_range"}))
	assert.Equal(t, "UserExpiring", pySubjectRefName(schema.SubjectType{Definition: "user", Expiration: true}))

	// Relation must win when combined with a caveat (sealed-union emitters in
	// later tasks rely on this branch order).
	assert.Equal(t, "TeamMember", pySubjectRefName(schema.SubjectType{
		Definition: "team", Relation: "member", CaveatName: "ip_range",
	}))
}

func TestCaveatParamKeywordCollision(t *testing.T) {
	s := &schema.Schema{
		Caveats: []schema.CaveatDefinition{
			{Name: "needs_id", Params: []schema.CaveatParam{{Name: "id", Type: "string"}}},
		},
		Definitions: []schema.Definition{
			{
				Name: "thing",
				Relations: []schema.Relation{
					{
						Name: "viewer",
						AllowedSubjects: []schema.SubjectType{
							{Definition: "user", CaveatName: "needs_id"},
						},
					},
				},
			},
		},
	}

	g := &Generator{}
	files, err := g.Generate(s, nil)
	require.NoError(t, err)
	output := string(files[0].Content)

	assert.Contains(t, output, "id_: str | None = None",
		"keyword-conflicting param should be escaped on the dataclass field")
	assert.Contains(t, output, `d["id"] = self.id_`,
		"_to_dict must use the raw schema name as the dict key, not the escaped identifier")
}

// TestDualRoleDefinitionRejected ensures the generator refuses to emit a
// schema where the same definition is both used as a base subject and carries
// its own permissions/relations/sub-refs. Without this guard, the generated
// file would contain two `class X:` declarations and Python would let the
// second silently win, breaking the subject-ref's caveat builders.
func TestDualRoleDefinitionRejected(t *testing.T) {
	s := &schema.Schema{
		Definitions: []schema.Definition{
			{
				Name: "user",
				Relations: []schema.Relation{
					// user.friend: user — makes "user" appear as a base subject
					// AND gives the user definition a relation of its own.
					{
						Name: "friend",
						AllowedSubjects: []schema.SubjectType{
							{Definition: "user"},
						},
					},
				},
			},
		},
	}

	g := &Generator{}
	_, err := g.Generate(s, nil)
	require.Error(t, err, "dual-role definition must be rejected")
	assert.Contains(t, err.Error(), `"user"`)
	assert.Contains(t, err.Error(), "both")
}
