// Code generated by spicedb-gen. DO NOT EDIT.

import {
    SpiceDBClient,
    createSpiceDBClient,
    Transaction,
    type Relationship,
} from "@spicedb/client";
import { full } from "@spicedb/client";
type Consistency = ReturnType<typeof full>;

// --- Types ---
type UserRef = { _type: "user"; _id: string };
type TeamRef = { _type: "team"; _id: string };
type TeamMemberRef = { _type: "team"; _id: string; _relation: "member" };
type DocumentRef = { _type: "document"; _id: string };

// --- Factories ---

export function User(id: string): UserRef {
    return { _type: "user", _id: id };
}

export function Team(id: string) {
    return {
        _type: "team" as const,
        _id: id,
        // Relations
        member: (subject: UserRef | TeamMemberRef) => ({
            _type: "team" as const, _id: id,
            _relation: "member" as const, _subject: subject,
        }),
    };
}
Team.member = (id: string): TeamMemberRef => ({
    _type: "team", _id: id, _relation: "member",
});

export function Document(id: string) {
    return {
        _type: "document" as const,
        _id: id,
        // Permissions
        view: { _type: "document" as const, _id: id, _permission: "view" as const },
        edit: { _type: "document" as const, _id: id, _permission: "edit" as const },
        delete: { _type: "document" as const, _id: id, _permission: "delete" as const },
        // Relations
        viewer: (subject: UserRef | TeamMemberRef) => ({
            _type: "document" as const, _id: id,
            _relation: "viewer" as const, _subject: subject,
        }),
        editor: (subject: UserRef) => ({
            _type: "document" as const, _id: id,
            _relation: "editor" as const, _subject: subject,
        }),
        owner: (subject: UserRef) => ({
            _type: "document" as const, _id: id,
            _relation: "owner" as const, _subject: subject,
        }),
    };
}
Document.view = { _type: "document" as const, _permission: "view" as const };
Document.edit = { _type: "document" as const, _permission: "edit" as const };
Document.delete = { _type: "document" as const, _permission: "delete" as const };

// --- TypedClient ---
export class TypedClient {
    readonly client: SpiceDBClient;

    constructor(client: SpiceDBClient) {
        this.client = client;
    }

    static create(endpoint: string, token: string, options?: { insecure?: boolean }): TypedClient {
        return new TypedClient(createSpiceDBClient(endpoint, token, options));
    }

    // Check overloads
    async check(c: Consistency, p: { _type: "document"; _id: string; _permission: "view" }, s: UserRef | TeamMemberRef): Promise<boolean>;
    async check(c: Consistency, p: { _type: "document"; _id: string; _permission: "edit" }, s: UserRef): Promise<boolean>;
    async check(c: Consistency, p: { _type: "document"; _id: string; _permission: "delete" }, s: UserRef): Promise<boolean>;
    async check(c: Consistency, p: { _type: string; _id: string; _permission: string }, s: { _type: string; _id: string; _relation?: string }): Promise<boolean> {
        return this.client.checkPermission(c, {
            resourceType: p._type, resourceId: p._id, permission: p._permission,
            subjectType: s._type, subjectId: s._id, subjectRelation: (s as any)._relation,
        });
    }

    // Write operations
    async touch(...rels: Array<{ _type: string; _relation: string; _id: string; _subject: { _type: string; _id: string; _relation?: string } }>): Promise<string> {
        const txn = new Transaction();
        for (const r of rels) {
            txn.touch({ resourceType: r._type, resourceId: r._id, resourceRelation: r._relation,
                        subjectType: r._subject._type, subjectId: r._subject._id, subjectRelation: r._subject._relation });
        }
        return this.client.write(txn);
    }

    async create(...rels: Array<{ _type: string; _relation: string; _id: string; _subject: { _type: string; _id: string; _relation?: string } }>): Promise<string> {
        const txn = new Transaction();
        for (const r of rels) {
            txn.create({ resourceType: r._type, resourceId: r._id, resourceRelation: r._relation,
                         subjectType: r._subject._type, subjectId: r._subject._id, subjectRelation: r._subject._relation });
        }
        return this.client.write(txn);
    }

    async delete(...rels: Array<{ _type: string; _relation: string; _id: string; _subject: { _type: string; _id: string; _relation?: string } }>): Promise<string> {
        const txn = new Transaction();
        for (const r of rels) {
            txn.delete({ resourceType: r._type, resourceId: r._id, resourceRelation: r._relation,
                         subjectType: r._subject._type, subjectId: r._subject._id, subjectRelation: r._subject._relation });
        }
        return this.client.write(txn);
    }

    // LookupResources overloads
    async lookupResources(c: Consistency, p: { _type: "document"; _permission: "view" }, s: UserRef | TeamMemberRef): Promise<AsyncIterableIterator<string>>;
    async lookupResources(c: Consistency, p: { _type: "document"; _permission: "edit" }, s: UserRef): Promise<AsyncIterableIterator<string>>;
    async lookupResources(c: Consistency, p: { _type: "document"; _permission: "delete" }, s: UserRef): Promise<AsyncIterableIterator<string>>;
    async lookupResources(c: Consistency, p: { _type: string; _permission: string }, s: { _type: string; _id: string; _relation?: string }): Promise<AsyncIterableIterator<string>> {
        return this.client.lookupResources({
            resourceType: p._type, permission: p._permission,
            subjectType: s._type, subjectId: s._id, subjectRelation: (s as any)._relation,
        }, c);
    }

    // LookupSubjects overloads
    async lookupSubjects(c: Consistency, p: { _type: "document"; _id: string; _permission: "view" }, subjectType: (id: string) => { _type: string }): Promise<AsyncIterableIterator<string>>;
    async lookupSubjects(c: Consistency, p: { _type: "document"; _id: string; _permission: "edit" }, subjectType: (id: string) => { _type: string }): Promise<AsyncIterableIterator<string>>;
    async lookupSubjects(c: Consistency, p: { _type: "document"; _id: string; _permission: "delete" }, subjectType: (id: string) => { _type: string }): Promise<AsyncIterableIterator<string>>;
    async lookupSubjects(c: Consistency, p: { _type: string; _id: string; _permission: string }, subjectType: (id: string) => { _type: string }): Promise<AsyncIterableIterator<string>> {
        return this.client.lookupSubjects({
            subjectType: subjectType("")._type,
            permission: p._permission,
            resourceType: p._type,
            resourceId: p._id,
        }, c);
    }

    // ReadRelationships
    readRelationships(c: Consistency, filter: { _type: string; _relation?: string }): AsyncIterableIterator<Relationship> {
        return this.client.readRelationships({
            resourceType: filter._type, resourceRelation: filter._relation,
        }, c);
    }
}
