// Code generated by spicedb-gen. DO NOT EDIT.

import {
    SpiceDBClient,
    createSpiceDBClient,
    Transaction,
    CheckResult,
    type Relationship,
    type LookupResource,
    type LookupSubject,
    type CheckOptions,
} from "@spicedb/client";
import { full } from "@spicedb/client";
type Consistency = ReturnType<typeof full>;

// --- Caveat Contexts ---
export interface IpRangeContext {
    allowedCidr?: string;
}
// ipRangeContextToRaw translates IpRangeContext's camelCase, TypeScript-facing field
// names back to the RAW schema parameter names SpiceDB's CEL evaluator looks up (e.g.
// "allowedCidr" -> "allowed_cidr"). A field left undefined is omitted entirely, not sent as an
// explicit null/undefined value.
function ipRangeContextToRaw(ctx: IpRangeContext): Record<string, unknown> {
    const raw: Record<string, unknown> = {};
    if (ctx.allowedCidr !== undefined) raw["allowed_cidr"] = ctx.allowedCidr;
    return raw;
}
export interface TimeWindowContext {
    end?: string;
    start?: string;
}
// timeWindowContextToRaw translates TimeWindowContext's camelCase, TypeScript-facing field
// names back to the RAW schema parameter names SpiceDB's CEL evaluator looks up (e.g.
// "allowedCidr" -> "allowed_cidr"). A field left undefined is omitted entirely, not sent as an
// explicit null/undefined value.
function timeWindowContextToRaw(ctx: TimeWindowContext): Record<string, unknown> {
    const raw: Record<string, unknown> = {};
    if (ctx.end !== undefined) raw["end"] = ctx.end;
    if (ctx.start !== undefined) raw["start"] = ctx.start;
    return raw;
}

// --- Types ---
type UserRef = { _type: "user"; _id: string; _caveat?: never };
type TeamRef = { _type: "team"; _id: string; _caveat?: never };
type TeamMemberRef = { _type: "team"; _id: string; _relation: "member"; _caveat?: never };
type DocumentRef = { _type: "document"; _id: string; _caveat?: never };
type UserIpRangeRef = { _type: "user"; _id: string; _caveat: "ip_range"; _caveatContext: Record<string, unknown> };
type UserTimeWindowRef = { _type: "user"; _id: string; _caveat: "time_window"; _caveatContext: Record<string, unknown> };

// --- Factories ---

export function User(id: string) {
    return {
        _type: "user" as const,
        _id: id,
        _caveat: undefined as undefined,
        // Caveat methods
        withIpRange: (ctx: IpRangeContext): UserIpRangeRef => ({
            _type: "user", _id: id, _caveat: "ip_range" as const, _caveatContext: ipRangeContextToRaw(ctx),
        }),
        withTimeWindow: (ctx: TimeWindowContext): UserTimeWindowRef => ({
            _type: "user", _id: id, _caveat: "time_window" as const, _caveatContext: timeWindowContextToRaw(ctx),
        }),
    };
}

export function Team(id: string) {
    return {
        _type: "team" as const,
        _id: id,
        // Relations
        member: ((subject?: UserRef | TeamMemberRef): TeamMemberRef | { _type: "team"; _id: string; _relation: "member"; _subject: UserRef | TeamMemberRef } => subject === undefined
            ? ({ _type: "team", _id: id, _relation: "member" }) as TeamMemberRef
            : ({ _type: "team" as const, _id: id, _relation: "member" as const, _subject: subject })) as { (): TeamMemberRef; (subject: UserRef | TeamMemberRef): { _type: "team"; _id: string; _relation: "member"; _subject: UserRef | TeamMemberRef } },
    };
}

export function Document(id: string) {
    return {
        _type: "document" as const,
        _id: id,
        // Permissions
        view: { _type: "document" as const, _id: id, _permission: "view" as const },
        edit: { _type: "document" as const, _id: id, _permission: "edit" as const },
        delete: { _type: "document" as const, _id: id, _permission: "delete" as const },
        // Relations
        viewer: (subject: UserRef | UserIpRangeRef | UserTimeWindowRef | TeamMemberRef) => ({
            _type: "document" as const, _id: id,
            _relation: "viewer" as const, _subject: subject,
        }),
        editor: (subject: UserRef) => ({
            _type: "document" as const, _id: id,
            _relation: "editor" as const, _subject: subject,
        }),
        owner: (subject: UserRef) => ({
            _type: "document" as const, _id: id,
            _relation: "owner" as const, _subject: subject,
        }),
    };
}
Document.view = { _type: "document" as const, _permission: "view" as const };
Document.edit = { _type: "document" as const, _permission: "edit" as const };
Document.delete = { _type: "document" as const, _permission: "delete" as const };

// --- TypedClient ---
export class TypedClient {
    readonly client: SpiceDBClient;

    constructor(client: SpiceDBClient) {
        this.client = client;
    }

    static create(endpoint: string, token: string, options?: { insecure?: boolean }): TypedClient {
        return new TypedClient(createSpiceDBClient(endpoint, token, options));
    }

    // Check overloads
    async check(c: Consistency, p: { _type: "document"; _id: string; _permission: "view" }, s: UserRef | UserIpRangeRef | UserTimeWindowRef | TeamMemberRef, options?: CheckOptions): Promise<CheckResult>;
    async check(c: Consistency, p: { _type: "document"; _id: string; _permission: "edit" }, s: UserRef, options?: CheckOptions): Promise<CheckResult>;
    async check(c: Consistency, p: { _type: "document"; _id: string; _permission: "delete" }, s: UserRef, options?: CheckOptions): Promise<CheckResult>;
    async check(c: Consistency, p: { _type: string; _id: string; _permission: string }, s: { _type: string; _id: string; _relation?: string; _caveat?: string; _caveatContext?: Record<string, any> }, options?: CheckOptions): Promise<CheckResult> {
        // s._caveatContext (e.g. from User("dave").withIpRange(ctx)) is the
        // ITEM-LEVEL context for this one check -- it wins per-key over
        // options.context (the call-level default) via checkPermission's own
        // mergeCheckContext; call-level keys the subject doesn't mention are
        // retained.
        return this.client.checkPermission(c, {
            resourceType: p._type, resourceId: p._id, permission: p._permission,
            subjectType: s._type, subjectId: s._id, subjectRelation: (s as any)._relation,
            context: s._caveatContext,
        }, options);
    }

    // Write operations
    async touch(...rels: Array<{ _type: string; _relation: string; _id: string; _subject: { _type: string; _id: string; _relation?: string; _caveat?: string; _caveatContext?: Record<string, any> } }>): Promise<string> {
        const txn = new Transaction();
        for (const r of rels) {
            txn.touch({ resourceType: r._type, resourceId: r._id, resourceRelation: r._relation,
                        subjectType: r._subject._type, subjectId: r._subject._id, subjectRelation: r._subject._relation,
                        caveatName: r._subject._caveat, caveatContext: r._subject._caveatContext as any });
        }
        return this.client.write(txn);
    }

    async create(...rels: Array<{ _type: string; _relation: string; _id: string; _subject: { _type: string; _id: string; _relation?: string; _caveat?: string; _caveatContext?: Record<string, any> } }>): Promise<string> {
        const txn = new Transaction();
        for (const r of rels) {
            txn.create({ resourceType: r._type, resourceId: r._id, resourceRelation: r._relation,
                         subjectType: r._subject._type, subjectId: r._subject._id, subjectRelation: r._subject._relation,
                         caveatName: r._subject._caveat, caveatContext: r._subject._caveatContext as any });
        }
        return this.client.write(txn);
    }

    async delete(...rels: Array<{ _type: string; _relation: string; _id: string; _subject: { _type: string; _id: string; _relation?: string; _caveat?: string; _caveatContext?: Record<string, any> } }>): Promise<string> {
        const txn = new Transaction();
        for (const r of rels) {
            txn.delete({ resourceType: r._type, resourceId: r._id, resourceRelation: r._relation,
                         subjectType: r._subject._type, subjectId: r._subject._id, subjectRelation: r._subject._relation,
                         caveatName: r._subject._caveat, caveatContext: r._subject._caveatContext as any });
        }
        return this.client.write(txn);
    }

    // LookupResources overloads
    async lookupResources(c: Consistency, p: { _type: "document"; _permission: "view" }, s: UserRef | UserIpRangeRef | UserTimeWindowRef | TeamMemberRef): Promise<AsyncIterableIterator<LookupResource>>;
    async lookupResources(c: Consistency, p: { _type: "document"; _permission: "edit" }, s: UserRef): Promise<AsyncIterableIterator<LookupResource>>;
    async lookupResources(c: Consistency, p: { _type: "document"; _permission: "delete" }, s: UserRef): Promise<AsyncIterableIterator<LookupResource>>;
    async lookupResources(c: Consistency, p: { _type: string; _permission: string }, s: { _type: string; _id: string; _relation?: string }): Promise<AsyncIterableIterator<LookupResource>> {
        return this.client.lookupResources({
            resourceType: p._type, permission: p._permission,
            subjectType: s._type, subjectId: s._id, subjectRelation: (s as any)._relation,
        }, c);
    }

    // LookupSubjects overloads
    async lookupSubjects(c: Consistency, p: { _type: "document"; _id: string; _permission: "view" }, subjectType: (id: string) => { _type: string }): Promise<AsyncIterableIterator<LookupSubject>>;
    async lookupSubjects(c: Consistency, p: { _type: "document"; _id: string; _permission: "edit" }, subjectType: (id: string) => { _type: string }): Promise<AsyncIterableIterator<LookupSubject>>;
    async lookupSubjects(c: Consistency, p: { _type: "document"; _id: string; _permission: "delete" }, subjectType: (id: string) => { _type: string }): Promise<AsyncIterableIterator<LookupSubject>>;
    async lookupSubjects(c: Consistency, p: { _type: string; _id: string; _permission: string }, subjectType: (id: string) => { _type: string }): Promise<AsyncIterableIterator<LookupSubject>> {
        return this.client.lookupSubjects({
            subjectType: subjectType("")._type,
            permission: p._permission,
            resourceType: p._type,
            resourceId: p._id,
        }, c);
    }

    // ReadRelationships
    readRelationships(c: Consistency, filter: { _type: string; _relation?: string }): AsyncIterableIterator<Relationship> {
        return this.client.readRelationships({
            resourceType: filter._type, resourceRelation: filter._relation,
        }, c);
    }
}
