//! SpiceDB Proto Client for Rust
//!
//! This crate provides a thin wrapper over tonic-generated gRPC stubs for
//! SpiceDB. The generated types are produced by `tonic-build` from proto files
//! exported via `buf export buf.build/authzed/api -o proto`.
//!
//! # Usage
//!
//! ```rust,no_run
//! use spicedb_proto::SpiceDBProtoClient;
//!
//! #[tokio::main]
//! async fn main() -> Result<(), Box<dyn std::error::Error>> {
//!     let client = SpiceDBProtoClient::new("grpc.authzed.com:443", "my-token", false).await?;
//!     // Use client.permissions, client.schema, client.watch, client.experimental
//!     Ok(())
//! }
//! ```

pub mod client;

// Proto module includes. These are generated by tonic-build from the proto/
// directory. They will only be available after running:
//   buf export buf.build/authzed/api -o proto
//   cargo build
//
// Once generated, the modules are included like:
//   pub mod authzed {
//       pub mod api {
//           pub mod v1 {
//               tonic::include_proto!("authzed.api.v1");
//           }
//       }
//   }
//
// For now, these are commented out since proto/ does not exist yet.
// Uncomment after running buf export and cargo build.

// pub mod authzed {
//     pub mod api {
//         pub mod v1 {
//             tonic::include_proto!("authzed.api.v1");
//         }
//     }
// }

pub use client::SpiceDBProtoClient;
