//! SpiceDB Proto Client for Rust
//!
//! This crate provides a thin wrapper over tonic-generated gRPC stubs for
//! SpiceDB. The generated types are produced by `tonic-build` from proto files
//! exported via `buf export buf.build/authzed/api -o proto`.
//!
//! # Usage
//!
//! ```rust,no_run
//! use spicedb_proto::SpiceDBProtoClient;
//!
//! #[tokio::main]
//! async fn main() -> Result<(), Box<dyn std::error::Error>> {
//!     let client = SpiceDBProtoClient::new("grpc.authzed.com:443", "my-token", false).await?;
//!     // Use client.permissions, client.schema, client.watch, client.experimental
//!     Ok(())
//! }
//! ```

pub mod client;

// Proto module includes. These are generated by tonic-build from the proto/
// directory.
pub mod google {
    pub mod rpc {
        tonic::include_proto!("google.rpc");
    }
}

pub mod authzed {
    pub mod api {
        pub mod v1 {
            tonic::include_proto!("authzed.api.v1");
        }
    }
}

pub use client::SpiceDBProtoClient;
