services:
  spicedb:
    image: authzed/spicedb:latest
    command: serve --grpc-preshared-key=${SPICEDB_TEST_TOKEN:-somerandomkeyhere} --datastore-engine=memory
    ports:
      - "${SPICEDB_TEST_PORT:-50051}:50051"
    healthcheck:
      test: ["CMD", "grpc_health_probe", "-addr=:50051"]
      interval: 2s
      timeout: 5s
      retries: 10
