// Code generated by spicedb-gen. DO NOT EDIT.

package permissions

import (
	"context"
	"iter"
	"time"

	"github.com/authzed/spicedb-clients/spicedb-go/client"
	"github.com/authzed/spicedb-clients/spicedb-go/consistency"
	"github.com/authzed/spicedb-clients/spicedb-go/rel"
)

// --- Base Types ---

// Subject is the sealed interface for all subject reference types.
type Subject interface {
	subjectRef() (string, string, string)
	caveatInfo() (string, map[string]any)
	expirationTime() *time.Time
}

// Permission represents a permission check target (resource + permission).
type Permission struct {
	resourceType string
	resourceID   string
	permission   string
}

// PermissionRef represents a permission reference without a specific resource ID (for LookupResources).
type PermissionRef struct {
	resourceType string
	permission   string
}

// TypedRelationship wraps a rel.Relationship with type safety.
type TypedRelationship struct {
	r rel.Relationship
}

// TypedClient wraps a SpiceDB client with type-safe methods.
type TypedClient struct {
	Client *client.Client
}

// NewTypedClient creates a new TypedClient wrapping the given SpiceDB client.
func NewTypedClient(c *client.Client) *TypedClient {
	return &TypedClient{Client: c}
}

// --- Caveat Context Types ---

// IpRangeContext holds context parameters for the ip_range caveat.
type IpRangeContext struct {
	AllowedCidr *string
}

func (c IpRangeContext) WithAllowedCidr(v string) IpRangeContext {
	c.AllowedCidr = &v
	return c
}

func (c IpRangeContext) toMap() map[string]any {
	m := make(map[string]any)
	if c.AllowedCidr != nil {
		m["allowed_cidr"] = *c.AllowedCidr
	}
	return m
}

// TimeWindowContext holds context parameters for the time_window caveat.
type TimeWindowContext struct {
	End *string
	Start *string
}

func (c TimeWindowContext) WithEnd(v string) TimeWindowContext {
	c.End = &v
	return c
}

func (c TimeWindowContext) WithStart(v string) TimeWindowContext {
	c.Start = &v
	return c
}

func (c TimeWindowContext) toMap() map[string]any {
	m := make(map[string]any)
	if c.End != nil {
		m["end"] = *c.End
	}
	if c.Start != nil {
		m["start"] = *c.Start
	}
	return m
}

// --- Subject Ref Types ---

type UserRef struct {
	id string
}

func (r UserRef) subjectRef() (string, string, string) {
	return "user", r.id, ""
}

func (r UserRef) caveatInfo() (string, map[string]any) {
	return "", nil
}

func (r UserRef) expirationTime() *time.Time {
	return nil
}

func (r UserRef) WithIpRange(ctx IpRangeContext) UserIpRange {
	return UserIpRange{id: r.id, context: ctx}
}

func (r UserRef) WithTimeWindow(ctx TimeWindowContext) UserTimeWindow {
	return UserTimeWindow{id: r.id, context: ctx}
}


type UserIpRange struct {
	id      string
	context IpRangeContext
}

func (r UserIpRange) subjectRef() (string, string, string) {
	return "user", r.id, ""
}

func (r UserIpRange) caveatInfo() (string, map[string]any) {
	return "ip_range", r.context.toMap()
}

func (r UserIpRange) expirationTime() *time.Time {
	return nil
}

type UserTimeWindow struct {
	id      string
	context TimeWindowContext
}

func (r UserTimeWindow) subjectRef() (string, string, string) {
	return "user", r.id, ""
}

func (r UserTimeWindow) caveatInfo() (string, map[string]any) {
	return "time_window", r.context.toMap()
}

func (r UserTimeWindow) expirationTime() *time.Time {
	return nil
}

type TeamMemberRef struct {
	id string
}

func (r TeamMemberRef) subjectRef() (string, string, string) {
	return "team", r.id, "member"
}

func (r TeamMemberRef) caveatInfo() (string, map[string]any) {
	return "", nil
}

func (r TeamMemberRef) expirationTime() *time.Time {
	return nil
}

// --- Type Sentinels ---

// UserType is a type sentinel for LookupSubjects.
var UserType = userRefType{}

type userRefType struct{}

func (userRefType) subjectRef() (string, string, string) {
	return "user", "", ""
}

func (userRefType) caveatInfo() (string, map[string]any) {
	return "", nil
}

func (userRefType) expirationTime() *time.Time {
	return nil
}

func (userRefType) isTeamMemberSubject() {}
func (userRefType) isDocumentViewerSubject() {}
func (userRefType) isDocumentEditorSubject() {}
func (userRefType) isDocumentOwnerSubject() {}
func (userRefType) isDocumentViewSubject() {}
func (userRefType) isDocumentEditSubject() {}
func (userRefType) isDocumentDeleteSubject() {}

// TeamMemberType is a type sentinel for LookupSubjects.
var TeamMemberType = teamMemberRefType{}

type teamMemberRefType struct{}

func (teamMemberRefType) subjectRef() (string, string, string) {
	return "team", "", "member"
}

func (teamMemberRefType) caveatInfo() (string, map[string]any) {
	return "", nil
}

func (teamMemberRefType) expirationTime() *time.Time {
	return nil
}

func (teamMemberRefType) isTeamMemberSubject() {}
func (teamMemberRefType) isDocumentViewerSubject() {}
func (teamMemberRefType) isDocumentViewSubject() {}

// --- Constructors ---

// User creates a new UserRef with the given ID.
func User(id string) UserRef {
	return UserRef{id: id}
}

// TeamRef represents a reference to a team resource.
type TeamRef struct {
	id string
}

// Team creates a new TeamRef with the given ID.
func Team(id string) TeamRef {
	return TeamRef{id: id}
}

// DocumentRef represents a reference to a document resource.
type DocumentRef struct {
	id string
}

// Document creates a new DocumentRef with the given ID.
func Document(id string) DocumentRef {
	return DocumentRef{id: id}
}

// --- SubRef Methods ---

// Member returns a TeamMemberRef for this team.
func (r TeamRef) Member() TeamMemberRef {
	return TeamMemberRef{id: r.id}
}


// --- Sealed Subject Interfaces ---

// TeamMemberSubject is a sealed interface for subjects allowed in this position.
type TeamMemberSubject interface {
	Subject
	isTeamMemberSubject()
}

func (TeamMemberRef) isTeamMemberSubject() {}
func (UserRef) isTeamMemberSubject() {}

// DocumentViewerSubject is a sealed interface for subjects allowed in this position.
type DocumentViewerSubject interface {
	Subject
	isDocumentViewerSubject()
}

func (TeamMemberRef) isDocumentViewerSubject() {}
func (UserIpRange) isDocumentViewerSubject() {}
func (UserRef) isDocumentViewerSubject() {}
func (UserTimeWindow) isDocumentViewerSubject() {}

// DocumentEditorSubject is a sealed interface for subjects allowed in this position.
type DocumentEditorSubject interface {
	Subject
	isDocumentEditorSubject()
}

func (UserRef) isDocumentEditorSubject() {}

// DocumentOwnerSubject is a sealed interface for subjects allowed in this position.
type DocumentOwnerSubject interface {
	Subject
	isDocumentOwnerSubject()
}

func (UserRef) isDocumentOwnerSubject() {}

// DocumentViewSubject is a sealed interface for subjects allowed in this position.
type DocumentViewSubject interface {
	Subject
	isDocumentViewSubject()
}

func (TeamMemberRef) isDocumentViewSubject() {}
func (UserIpRange) isDocumentViewSubject() {}
func (UserRef) isDocumentViewSubject() {}
func (UserTimeWindow) isDocumentViewSubject() {}

// DocumentEditSubject is a sealed interface for subjects allowed in this position.
type DocumentEditSubject interface {
	Subject
	isDocumentEditSubject()
}

func (UserRef) isDocumentEditSubject() {}

// DocumentDeleteSubject is a sealed interface for subjects allowed in this position.
type DocumentDeleteSubject interface {
	Subject
	isDocumentDeleteSubject()
}

func (UserRef) isDocumentDeleteSubject() {}

// --- Permission Accessors ---

// View returns a Permission for checking view on this document.
func (d DocumentRef) View() Permission {
	return Permission{resourceType: "document", resourceID: d.id, permission: "view"}
}

// Edit returns a Permission for checking edit on this document.
func (d DocumentRef) Edit() Permission {
	return Permission{resourceType: "document", resourceID: d.id, permission: "edit"}
}

// Delete returns a Permission for checking delete on this document.
func (d DocumentRef) Delete() Permission {
	return Permission{resourceType: "document", resourceID: d.id, permission: "delete"}
}


// --- Static Permission Ref Vars ---
var (
	Document_View = PermissionRef{resourceType: "document", permission: "view"}
	Document_Edit = PermissionRef{resourceType: "document", permission: "edit"}
	Document_Delete = PermissionRef{resourceType: "document", permission: "delete"}
)

// --- Relation Methods ---

// ForMember creates a TypedRelationship for the member relation on this team.
func (d TeamRef) ForMember(subject TeamMemberSubject) TypedRelationship {
	sType, sID, sRel := subject.subjectRef()
	r := rel.MustFromTriple("team", d.id, "member", sType, sID, sRel)
	if cName, cCtx := subject.caveatInfo(); cName != "" {
		r = r.WithCaveat(cName, cCtx)
	}
	if exp := subject.expirationTime(); exp != nil {
		r = r.WithExpiration(*exp)
	}
	return TypedRelationship{r: r}
}

// Viewer creates a TypedRelationship for the viewer relation on this document.
func (d DocumentRef) Viewer(subject DocumentViewerSubject) TypedRelationship {
	sType, sID, sRel := subject.subjectRef()
	r := rel.MustFromTriple("document", d.id, "viewer", sType, sID, sRel)
	if cName, cCtx := subject.caveatInfo(); cName != "" {
		r = r.WithCaveat(cName, cCtx)
	}
	if exp := subject.expirationTime(); exp != nil {
		r = r.WithExpiration(*exp)
	}
	return TypedRelationship{r: r}
}

// Editor creates a TypedRelationship for the editor relation on this document.
func (d DocumentRef) Editor(subject DocumentEditorSubject) TypedRelationship {
	sType, sID, sRel := subject.subjectRef()
	r := rel.MustFromTriple("document", d.id, "editor", sType, sID, sRel)
	if cName, cCtx := subject.caveatInfo(); cName != "" {
		r = r.WithCaveat(cName, cCtx)
	}
	if exp := subject.expirationTime(); exp != nil {
		r = r.WithExpiration(*exp)
	}
	return TypedRelationship{r: r}
}

// Owner creates a TypedRelationship for the owner relation on this document.
func (d DocumentRef) Owner(subject DocumentOwnerSubject) TypedRelationship {
	sType, sID, sRel := subject.subjectRef()
	r := rel.MustFromTriple("document", d.id, "owner", sType, sID, sRel)
	if cName, cCtx := subject.caveatInfo(); cName != "" {
		r = r.WithCaveat(cName, cCtx)
	}
	if exp := subject.expirationTime(); exp != nil {
		r = r.WithExpiration(*exp)
	}
	return TypedRelationship{r: r}
}


// --- Check and Lookup Functions ---

// Check checks whether the given subject has the specified permission on the
// resource.
//
// Check surfaces the underlying client's full CheckResult (Permissionship,
// MissingContext, CheckedAt) rather than collapsing it to a bool: a
// Conditional result means the server needed caveat context that was not
// supplied, and is NOT a grant. Prefer CheckResult.HasPermission() over
// comparing Permissionship directly for the common case.
//
// See CheckWithContext to supply a call-level caveat CHECK-TIME context for
// evaluating caveats encountered during the check (Check is CheckWithContext
// with a nil checkContext).
//
// A caveated subject ref (e.g. User("dave").WithIpRange(ctx)) supplies its
// own context to the check via rel.Relationship.WithCheckContext, the same
// accessor (subject.caveatInfo()) the write paths use to attach a caveat at
// write time -- but here it is applied to the ephemeral relationship built
// for this check only, never written.
func Check(ctx context.Context, tc *TypedClient, cs consistency.Strategy, perm Permission, subject Subject) (client.CheckResult, error) {
	sType, sID, sRel := subject.subjectRef()
	r, err := rel.FromTriple(perm.resourceType, perm.resourceID, perm.permission, sType, sID, sRel)
	if err != nil {
		return client.CheckResult{}, err
	}
	_, sCtx := subject.caveatInfo()
	r = r.WithCheckContext(sCtx)
	return tc.Client.CheckOne(ctx, cs, perm.permission, r)
}

// CheckWithContext is Check with a call-level default caveat CHECK-TIME
// context applied to the check, mirroring the underlying
// client.CheckOneWithContext. The subject's own context (see Check) is the
// ITEM-LEVEL value under client.CheckWithContext's merge rule: it wins
// per-key over this call-level checkContext, and call-level keys the subject
// doesn't mention are retained.
func CheckWithContext(ctx context.Context, tc *TypedClient, cs consistency.Strategy, perm Permission, checkContext map[string]any, subject Subject) (client.CheckResult, error) {
	sType, sID, sRel := subject.subjectRef()
	r, err := rel.FromTriple(perm.resourceType, perm.resourceID, perm.permission, sType, sID, sRel)
	if err != nil {
		return client.CheckResult{}, err
	}
	_, sCtx := subject.caveatInfo()
	r = r.WithCheckContext(sCtx)
	return tc.Client.CheckOneWithContext(ctx, cs, perm.permission, checkContext, r)
}

// LookupResources returns an iterator of resources that the subject has the specified permission on.
func LookupResources(ctx context.Context, tc *TypedClient, cs consistency.Strategy, perm PermissionRef, subject Subject) iter.Seq2[client.LookupResource, error] {
	sType, sID, _ := subject.subjectRef()
	return tc.Client.LookupResources(ctx, cs, perm.resourceType, perm.permission, sType, sID)
}

// LookupSubjects returns an iterator of subjects that have the specified permission on the resource.
func LookupSubjects(ctx context.Context, tc *TypedClient, cs consistency.Strategy, perm Permission, subjectType Subject) iter.Seq2[client.LookupSubject, error] {
	sType, _, _ := subjectType.subjectRef()
	return tc.Client.LookupSubjects(ctx, cs, perm.resourceType, perm.resourceID, perm.permission, sType)
}

// --- Write Methods ---

// Touch creates or updates the given relationships. It returns an error,
// without writing anything, if any relationship's caveat context cannot be
// converted to protobuf -- see rel.Relationship.ToProto.
func (tc *TypedClient) Touch(ctx context.Context, rels ...TypedRelationship) (string, error) {
	var txn rel.Txn
	for _, r := range rels {
		if err := txn.Touch(r.r); err != nil {
			return "", err
		}
	}
	return tc.Client.Write(ctx, txn)
}

// Create creates the given relationships, failing if they already exist. It
// returns an error, without writing anything, if any relationship's caveat
// context cannot be converted to protobuf -- see rel.Relationship.ToProto.
func (tc *TypedClient) Create(ctx context.Context, rels ...TypedRelationship) (string, error) {
	var txn rel.Txn
	for _, r := range rels {
		if err := txn.Create(r.r); err != nil {
			return "", err
		}
	}
	return tc.Client.Write(ctx, txn)
}

// Delete deletes the given relationships. It returns an error, without
// writing anything, if any relationship's caveat context cannot be converted
// to protobuf -- see rel.Relationship.ToProto.
func (tc *TypedClient) Delete(ctx context.Context, rels ...TypedRelationship) (string, error) {
	var txn rel.Txn
	for _, r := range rels {
		if err := txn.Delete(r.r); err != nil {
			return "", err
		}
	}
	return tc.Client.Write(ctx, txn)
}
